### PR TITLE
Issue #31 Resolved

### LINKED ISSUE #31: [BUG] Exit icon
The exit icon seems to have been squashed and it needs to be replaced.
It was supposed to be this one: ⓧ
image

### PR DESCRIPTION
**Pull request by Lokeshsuwalka05**
#31 Resolved

### CODE REVIEW

**Comment by Lokeshsuwalka05** [comment]
i think there is no more conflict.

**Review by eduardconstantin — APPROVED** [review]
Thank you for your contribution!

**Comment by Lokeshsuwalka05** [comment]
Are You on linkedin or X??
Can you give me Your Social Media Handle??

**Comment by eduardconstantin** [comment]
you can find me on x: https://x.com/_Eduard26

**Pull request merged**
